databases:
- name: djangoasync
  databaseName: djangoasync
  user: djangoasync

services:
- type: web
  name: djangoasync
  plan: free
  env: python
  buildCommand: "./build.sh"
  # startCommand: "gunicorn config.wsgi:application"
  startCommand: "gunicorn config.asgi:application -w 4 -k uvicorn.workers.UvicornWorker"
  autoDeploy: false
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: djangoasync
        property: connectionString
    # - key: DJANGO_SECRET_KEY
    # - key: DJANGO_SETTINGS_MODULE
    # - key: NUBLADO_BOT_TOKEN
    # - key: NUBLADO_GROUP_ID
    # - key: NUBLADO_GROUP_OWNER_ID
    # - key: NUBLADO_REPO_ID
    # - key: PORT
    - fromGroup: djangoasync