# Generated by Django 4.1.3 on 2023-01-02 09:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2)),
            ],
            options={
                'verbose_name': 'Bot configuration',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField()),
                ('group_id', models.BigIntegerField()),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('point_increment', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'unique_together': {('user_id', 'group_id')},
            },
        ),
    ]
